package com.Audi_Service.employees;

public enum JobTitles {

    PORTER,
    LEAD_PORTER,
    TECHNOLOGIST,
    SERVICE_ADVISOR,
    SERVICE_MANAGER,
    ASSISTANT_SERVICE_MANAGER,

    FLAT_RATE_TECHNICIAN,
    HOURLY_TECHNICIAN,
    SHOP_FOREMAN,
    SERVICE_DISPATCHER,

    PARTS_ASSOCIATE,
    SHIPPING_AND_RECEIVING,
    PARTS_MANAGER,

    SERVICE_DIRECTOR,
    GENERAL_MANAGER,

    DEALER_PRINCIPLE;
}
